---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP 
    runs-on: ubuntu-latest
    env:
      REPOSITORY: platform
      GKE_CLUSTER: cluster-1
      GKE_ZONE: us-central1-c 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
    
    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v0.7.0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Build Docker Image
      run: make PROJECT_ID=${{ secrets.PROJECT_ID }} build-push-image

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
        echo "$(pwd)/kustomize" >> $GITHUB_PATH

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: make PROJECT_ID=${{ secrets.PROJECT_ID }} deploy-image